### ISSUE TITLE
Map: icon logic with coloured mark does not work as expected

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/it.bz.opendatahub.analytics#21]
This logic is not working properly. 
The logics inserted here: https://github.com/noi-techpark/mobility-analytics/blob/master/src/main/webapp/layers-config.json
seems however correct
@davidebz can you please check?

**Comment by Piiit** [comment]
@davidebz @rcavaliere Has this issue been solved already?

**Comment by rcavaliere** [comment]
@Piiit not really, I will fix this in the config file. I will as short-term solution make a calculation based on the max occupancy of the parking areas, which we assume is forever fixed...
