### ISSUE TITLE
Map: icon logic with coloured mark independent from period

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/it.bz.opendatahub.analytics#22]
@davidebz For weather stations, we have different periods associated to the type "precipitation", since data providers are different. Can we modify the logic so that consider the value independently from the period?
E.g. 

 "icons": ["Weather.svg", ["green.svg", "precipitation", 300, 0, 1], ["yellow.svg", "precipitation", 300, 1, 10], ["red.svg", "precipitation", 300, 10, 99999]],

becomes

 "icons": ["Weather.svg", ["green.svg", "precipitation", 0, 1], ["yellow.svg", "precipitation", 1, 10], ["red.svg", "precipitation", 10, 99999]],

Will this work if we modify this like that?

**Comment by Piiit** [comment]
@davidebz @rcavaliere Is this issue still open for the new version of analytics?

**Comment by rcavaliere** [comment]
No, now with this new version we can manage this easily in the config file
