### ISSUE TITLE
As a project manager, I would like to create new users for the "analytics" web-app and assign them specific access rights for visualizing certain closed data

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/it.bz.opendatahub.analytics#24]
BrennerLEC partners and stakeholders do want to use the app now.

We will use this app as second app to bring on OAuth.

**Comment by rcavaliere** [comment]
First task is to implement API v2 + oAuth in the analytics web-app. Next steps:
- [ ] @Piiit prepares through externals (Martin) documentation on how to implement oAuth
- [ ] @rcavaliere asks an offer to Davide Montesin to do this implementation

**Comment by Piiit** [comment]
@ohnewein @rcavaliere All done, we just need to have a list of emails and users from brennerlec

Roberto will collect those and open new users and set rules with flightrules... let me know, if you need help...
