### ISSUE TITLE
As a maintainer of the analytics project, I want to cleanup the repository and have a minimal deployment setup

### ISSUE THREAD

**Issue by Piiit** [noi-techpark/it.bz.opendatahub.analytics#40]
- [x] Check if Java is still necessary
- [x] Check if it would be possible to put all to an s3 bucket, instead of a docker image
- [x] Remove unnecessary and deprecated files
- [x] Use node for local development
> for now we use just a python http server
- [x] Check if the .env script could be replaced by a bundler
> our dotenv-sed.sh is good enough for now

**Comment by noctho** [comment]
I can confirm that Java is no longer needed. Since we have integrated NOI Authentication and  changed the API calls from the middleware servlet directly to the API.
