### ISSUE TITLE
As a mobility expert I would like to connect https://analytics.opendatahub.bz.it/ via the ODH API v2 also for the plots part

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/it.bz.opendatahub.analytics#44]
Task assigned to Chris Mair. 
What is needed on ore side:
- [x] integrate the PR in our testing environment

To go into production 
- [x] update production pipelines on jenkins
- [x] configure access to keycloak @ opendatahub.bz.it (chris, davide, ttdigital, test4brennerlec)
> Waiting for BrennerLEC Email, rest done
> @rcavaliere will provide a list of emails from brennerlec and setup those accounts with the flightrules
> Duplicate of #24
- [x] write flightrule on how to add new users and link to the flightrule on how to create new groups (update deprecated parts) + link from this README to those flightrules
- [x] add new proxy settings for `it.bz.opendatahub.analytics.conf` with alias `analytics.mobility.bz.it`
- [x] Remove from proxy
- analytics.mobility.bz.it.conf
- analytics.opendatahub.bz.it.conf
- [x] Remove docker related images and running containers on docker02.testingmachine.eu
- [x] Remove all old installations of the current production environment
- [x] @rcavaliere and @Piiit should go through https://github.com/noi-techpark/it.bz.opendatahub.analytics/issues and close issues (or open new ones if necessary)
- [x] use the new edge api, test edge views
- [x] integrate new pr

**Comment by rcavaliere** [comment]
PR to integrate: #47
@Piiit has deployed on https://analytics.opendatahub.testingmachine.eu/
@rcavaliere tests the new web-application

**Comment by rcavaliere** [comment]
@Piiit seems not to work, the connection to the API has some issues?

**Comment by Piiit** [comment]
@rcavaliere Fixed, changed the test URI and forgot to update analytics

**Comment by rcavaliere** [comment]
@Piiit thanks. I suggest to go in production with this application. With the deployment, I would suggest to configure some user credentials with different access roles, so that we can then immediately start to use them. Please let's do this together so that I can then autonomously create and manage user credentials to be shared with 3rd parties users

**Comment by Piiit** [comment]
@rcavaliere We are live, but the edges do not work on maps, because the v2 with edges is not yet deployed on production, I will do that next week...

**Comment by Piiit** [comment]
@rcavaliere Edges work now, the new api is online...

Could you please close all issues that are no longer valid... thanks

**Comment by Piiit** [comment]
@rcavaliere Do you know which email or emails brennerlec likes to use for login?

**Comment by rcavaliere** [comment]
@Piiit I would suggest to create "real" user accounts (i.e. personal e-mail address). I will provide the complete list to be created

**Comment by Piiit** [comment]
@rcavaliere ok, I will write flightrules on how to add those emails, and so you could enable the accounts by ourself and with that test the documentation... ok?

**Comment by Piiit** [comment]
@rcavaliere Flightrules updated... see https://github.com/noi-techpark/documentation/blob/master/FLIGHTRULES.md#open-data-hub-mobility for details... you need to add new users, and probably also a new role, if you do not want to reuse the existing BLC role.
