### ISSUE TITLE
As a mobility expert I would like to have a R library to easily access the ODH data through the API v2

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/it.bz.opendatahub.analytics#45]
Task assigned to Chris Mair. 
What is needed on our side:
- [x] create a new repository (or use mobility analytics)
- [x] integrate the PR in our testing environment
- [x] move it to a new repo
- [x] retrieval of closed data (authentication through keycloak)
- [x] upload of final library version to correct repository -> https://github.com/noi-techpark/it.bz.opendatahub.analytics.libs (by @bertolla)
- [x] test by CISMA

**Comment by rcavaliere** [comment]
PR to integrate: https://github.com/noi-techpark/mobility-analytics/pull/47

**Comment by Piiit** [comment]
@rcavaliere Done, see https://analytics.opendatahub.testingmachine.eu/ for testing

What has this all to do with an R library?

**Comment by rcavaliere** [comment]
I made confusion with user story #44. Chris Mair has to provide also a R library for accessing the ODH API v2. I have updated the user stories accordingly

**Comment by rcavaliere** [comment]
Let's leave it as "blocked" until we receive here a PR

**Comment by chris-mair** [comment]
Hi,

see PR 54

https://github.com/noi-techpark/it.bz.opendatahub.analytics/pull/54

I made a new dir under the main repo api/R/ so we can add other
APIs in the future.

Note: OAuth2 authentication is not yet supported here.

I've tested this with R 3.5 in Debian 10 and R 4.0 in macOS 10.14.

-- Chris

**Comment by rcavaliere** [comment]
@Piiit can you please import the PR, prepare something testable, and manage with @chris-mair the authentication mechanism?

**Comment by Piiit** [comment]
@rcavaliere I merged the PR now, but why do we have such a generic API library inside analytics, which is a web application and has nothing to do (except for the name maybe), with libraries? Should we use a separate repo instead, or do you want to keep it like this?

**Comment by Piiit** [comment]
@rcavaliere @chris-mair What do you need for the authentication mechanism? I think, with the present client `odh-mobility-generic` everyone can already use it. We just need to get a token from the oauth server and then send with each GET a header with Authentication bearer tokens.

See https://docs.opendatahub.bz.it/en/latest/guidelines/authentication.html for further details... 
The chapter "Request an access token" is a bit outdated, please remove the `--data-urlencode 'client_secret=the_client_secret'` part, since it is no longer needed.

**Comment by rcavaliere** [comment]
> @rcavaliere I merged the PR now, but why do we have such a generic API library inside analytics, which is a web application and has nothing to do (except for the name maybe), with libraries? Should we use a separate repo instead, or do you want to keep it like this?

You are right, I think we made like this because it was something that emerged from a discussion related to the analytics tool. Please create a separate repo for that!

**Comment by chris-mair** [comment]
This has been moved to https://github.com/noi-techpark/it.bz.opendatahub.analytics.libs/ and note PR #2 there solves authentication too.

So we can tick the last checkbox and close this :)

-- Chris

**Comment by rcavaliere** [comment]
This user story should be completed. 
@bertolla please upload the last version of the R library in the correct repository: https://github.com/noi-techpark/it.bz.opendatahub.analytics.libs
Once available, the complete test of this module will be carried out by CISMA

**Comment by bertolla** [comment]
I merged the dev branch, there should not be more to do.

**Comment by rcavaliere** [comment]
@bertolla there is a new PR by @chris-mair with an example on how to use credentials, please accept it!
