### ISSUE TITLE
Icon and page title are still showing "bz analytics"

### ISSUE THREAD

**Issue by Piiit** [noi-techpark/it.bz.opendatahub.analytics#49]
we should replace that with our branded open data hub icons and colors?

**Comment by Piiit** [comment]
@rcavaliere What do you think?

**Comment by rcavaliere** [comment]
Of course, that would be the next step. The GUI is already available... if we want to change the analytics logo, this should be decided together
[200504_DesignCIMA.pdf](https://github.com/noi-techpark/it.bz.opendatahub.analytics/files/5246443/200504_DesignCIMA.pdf)

**Comment by Piiit** [comment]
@rcavaliere Nice design, but I miss the graphs part. Should we change the title in the meantime or postpone all design changes to a future version?

**Comment by rcavaliere** [comment]
@Piiit the plots will be like now, just with the new CSS for header, font etc. I see this as part of a new deployment of analytics. Let's now concentrate on the correct functioning of the interface with the APIv2

**Comment by rcavaliere** [comment]
@noctho we got a request to delete the "BZ" part of the logo. Could you please do this? You can directly change the logo file and get the text "Analytics" nearer to the left element of the logo

**Comment by davidebz** [comment]
@rcavaliere ok, but please assign first me, then I will assign noctho or me depending on internal organization

**Comment by rcavaliere** [comment]
@davidebz ok done, thanks for the feedback

**Comment by davidebz** [comment]
@rcavaliere @noctho will cut the logo. We are not designer so we try do to the best we can. When you are not satisfied with our change to the logo is still possibile that you ask to a designer and we then copy the logo in the repository

**Comment by noctho** [comment]
I have cut "BZ" out of the logo. Now you only see "Analytics" there:
https://github.com/noi-techpark/it.bz.opendatahub.analytics/blob/7954a739cf290a5a83d011ecfa45fb8dc0ec11a0/src/main/webapp/img/logo.svg

see #74

**Comment by rcavaliere** [comment]
@noctho the logo is fine!

**Comment by Piiit** [comment]
@rcavaliere Can we close this issue?
