### ISSUE TITLE
As a data analyst I would like to have a more efficient visualization of the ODH mobility data on http://analytics.opendatahub.bz.it/

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/it.bz.opendatahub.analytics#64]
Thanks to several adjustments of the "layers-config.json" file it is possible to have a more immediate view of what's happening in real-time in terms of mobility and traffic conditions

**Comment by rcavaliere** [comment]
JSON file updated, see PR https://github.com/noi-techpark/it.bz.opendatahub.analytics/commit/eb47988e6ba98c04ad1360725678921ec3762ceb

@bertolla @Piiit can somebody of you put this in production?

**Comment by bertolla** [comment]
Merged with master and deployed on production
