### ISSUE TITLE
As a mobility expert I would like to see the new GUI of analytics.opendatahub.bz.it implemented

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/it.bz.opendatahub.analytics#67]
Implemented by Catch & Solve
@bertolla can you please integrate the PR https://github.com/noi-techpark/it.bz.opendatahub.analytics/pull/66 so that we can test the new GUI?

Check on https://analytics.opendatahub.testingmachine.eu/

**Comment by rcavaliere** [comment]
@bertolla can you please integrate the PR #68? This should fix some little remaining bugs. Once tested I think we can go in production.

**Comment by noctho** [comment]
But before going in production, I'd like to clean up the code and delete all the deprecated files.

**Comment by rcavaliere** [comment]
@noctho ok, will you make a new PR?

**Comment by noctho** [comment]
Yes, I will open a new PR

**Comment by bertolla** [comment]
You can see the changes on testing: https://analytics.opendatahub.testingmachine.eu/

**Comment by rcavaliere** [comment]
@bertolla @noctho wonderful, all issues seem to be solved. Once we get the final PR I think we can go really go to production!

**Comment by noctho** [comment]
I have created now the final PR, see #69

**Comment by rcavaliere** [comment]
@noctho wonderful! @bertolla can you please integrate it?

**Comment by bertolla** [comment]
@rcavaliere I just deployed it, please check if everything is still working as expected and we go to production

**Comment by rcavaliere** [comment]
@bertolla also #70 is solved. Let's put the new version in production!
