### ISSUE TITLE
As an end-user I would like to see the map and not the charts view display at first

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/it.bz.opendatahub.analytics#71]
Many users are starting to ask to see the map when they enter in the application, even if empty without layers activated - and not the charts, since they use this after browsing in the map. 
@notcho can you configure this? I hope this can be done very quickly, or?

**Comment by davidebz** [comment]
@rcavaliere yes it should be a quick activity. we will to this

**Comment by noctho** [comment]
done, see #74
