### ISSUE TITLE
As an end-user I would like to see on analytics also the bike sharing data of Merano

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/it.bz.opendatahub.analytics#72]
At present we display on analytics only the stationtype "BikeStation", which however does not include the bike sharing service in Merano. By adding this API call:
https://mobility.api.opendatahub.bz.it/v2/flat,node/Bicycle/*/latest?where=sorigin.eq.%22BIKE_SHARING_MERANO%22
it would be possible to see also see the positions of bikes on the map and the associated data in the charts view.
@davidebz @noctho would this very simple to add in the code?

**Comment by davidebz** [comment]
@rcavaliere Is this simply a new layer? Or this should be added to an existing layer with specific code logic?

**Comment by rcavaliere** [comment]
No, this should be integrated in the bike sharing layer. While retrieving the other bike sharing data this additional data should be also asked. Is this possible?

**Comment by davidebz** [comment]
@rcavaliere @davidebz and @noctho we will estimate the effort, discuss it internally and the I will report to you how we can proced

**Comment by rcavaliere** [comment]
@davidebz perfect! please do not start implement, just give me first an estimation about the effort / complexity to do this.

**Comment by davidebz** [comment]
@rcavaliere ok!

**Comment by davidebz** [comment]
Hi Roberto, the effort is about 8h

For other questions feel free to contact me

**Comment by noctho** [comment]
done, see #74
