### ISSUE TITLE
As a mobility expert I would like to monitor the accesses to the portal analytics.opendatahub.bz.it/

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/it.bz.opendatahub.analytics#73]
The user story relates to the insertion of the Google Analytics monitoring in the website and the internal sharing of the view on the Google Analytics dashboard

**Comment by bertolla** [comment]
If we add google analytics, we would also need a cookie banner for the user to accept. Can Davide M. do that?

**Comment by rcavaliere** [comment]
Really? We have several websites (e.g. BrennerLEC) in which we have Google A. without cookie banner...

**Comment by davidebz** [comment]
Hi Roberto, I confirm with google analytics the use must have the right to accept/reject google analytics cookies. I have do this task  for s.virtuale.

**Comment by davidebz** [comment]
I just reviewed the code of s.virtuale. The issue is more complex, it's may depend on the google analytics  flag anonymize_ip=true. But I think we need to make a recap about this.

**Comment by Piiit** [comment]
Some time ago, we had a discussion about not using GA at all

```
...what do you think about switching from google to another tool for web
site analytics?

https://matomo.org/
```

But due to lack of time, we never started with a test to compare GA and Matomo... maybe it is time to get it done :-)

**Comment by bertolla** [comment]
It wouldn't change the fact that we need a cookie banner. And doing the selfhosting would increase the effort for this user story drastically, block further development and increase maintenance effort . Not a bad idea, but should be done in a seperate user-story where we discuss if we self host or if we use their cloud infrastructure.

@rcavaliere Can Davide create this cookiebanner(should be low effort and doable in no time) ?

Meanwhile we stay on GA, maybe @Piiit, you can create a dedicated meeting where we discuss about a migration or at least a first trial.

**Comment by Piiit** [comment]
@bertolla The final decision was to test it with one project and see if the dashboard is what we need. Then, if we like it, we can have a look at their SaaS offerings or host it ourselves, if feasible. I will forward the old email to you all....

**Comment by Piiit** [comment]
> Meanwhile we stay on GA
That is OK, we should not hurry, make a plan and do it right from the start.

> maybe @Piiit, you can create a dedicated meeting where we discuss about a migration or at least a first trial.
OK, I will just invite devs for the moment

**Comment by bertolla** [comment]
@rcavaliere I kinda miss your reply for the cookiebanner. Can Davide implement this? It is unrelated to what we are going to use

**Comment by rcavaliere** [comment]
@bertolla can you please provide an example of Google Analytics snippet you already use for another web-app, e.g. mobility.meran.eu?

**Comment by rcavaliere** [comment]
Status: task assigned to @davidebz, waiting for implementation

**Comment by bertolla** [comment]
I did some small changes on the pipeline and it's working correctly now.(on production)
I sent and invitation for analytics to @rcavaliere and @ohnewein

**Comment by rcavaliere** [comment]
I see this on my google analytics dashboard. And you @ohnewein?

**Comment by ohnewein** [comment]
Seams to work since May 20th again.
