### ISSUE TITLE
As a project manager I would like to visualize the layer "event" on analytics.opendatahub.com

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/it.bz.opendatahub.analytics#94]
- [x] Verify and integrate the PR by Giulio Roman: https://github.com/noi-techpark/it.bz.opendatahub.analytics/pull/93
- [x] Make the new PR available under  https://analytics.opendatahub.testingmachine.eu/ (testing environment)
- [x] Release on production
- [ ] New feature (web component) released also in the web components store

**Comment by dulvui** [comment]
@rcavaliere PR is now available on testing site

**Comment by rcavaliere** [comment]
@dulvui still to be tested, seems that some improvements in the data provided is needed.

**Comment by rcavaliere** [comment]
@dulvui let's close this issue by considering the issues found in https://github.com/noi-techpark/bdp-commons/issues/599 for the visualization of the events of the Province BZ. The data flow from the Data Collector seems now OK, but the application presents some strange behavior that needs to be corrected / improved

**Comment by rcavaliere** [comment]
Decision on how to visualize the data:

- if start_date and end_date are both available, then consider if the interval is inside the interval selected by the user
- if start_date is only available (no end_date): on map, visualize the event that have as start_date = today_date, on table, consider the start_date given by the user (all events that a date after this one as start_date should be visualized)

**Comment by dulvui** [comment]
@rcavaliere the map shows now events of the type 'STAU' and 'UNFALL' only for the last 24 hours. It looks much better now.
Let me know if you find other events that should be filtered for the last 24 hours

**Comment by rcavaliere** [comment]
@dulvui yes looks better but I don't know if we just visualize real-time data. See for example this event, it's of 10.4...

![Screenshot from 2023-06-29 18-28-11](https://github.com/noi-techpark/it.bz.opendatahub.analytics/assets/9825179/692604fa-4528-4ab9-92d0-d3efff78714d)

**Comment by dulvui** [comment]
@rcavaliere You are right, currently I show only the events of type `STAU` and `UNFALL` in realtime.
I could extend the list with other events, filter all types for real time. But so types like `BAUSTELLE` or other longer lasting events would show up only the first 24 hours.
What do you prefer?
1) all events are real time
2) extend real time event list

**Comment by rcavaliere** [comment]
@dulvui as said above, I would show on the map only the events which have start_date = today_date, so let's show the events only for 24 hours. The table view could be more complicated, it is ok as now it is. Anyway, I am thinking to have the map view a little bit more complex, with filters that you can allow you to visualize data as you prefer. But let's put this in another user story...

**Comment by rcavaliere** [comment]
Also the table view could be improved, by e.g. giving expressly the possibility to say if we want events "open end" to be shown or not. I will summarize all these improvements in a new user story

**Comment by dulvui** [comment]
@rcavaliere Now only realtime events and events that have a start date in the future are shown on testing.
I realized now that I applied this filters only to events of province bz. Should I apply this also to A22?

**Comment by rcavaliere** [comment]
@dulvui looks much better! If I compare now the visualization with https://verkehr.provinz.bz.it/default.asp I see that there are some events which now we don't show, I would like to investigate more why by looking the reference start_date and end_date. Let me give more to test this. Yes, apply this change also for A22 please!

**Comment by dulvui** [comment]
@rcavaliere okay, I will wait for your feedback. Now I applied it also to A22
