### ISSUE TITLE
As a Open Data Hub Mobility Data Consumer I would like to see the layer "Bike Parking" on analytics.opendatahub.com

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/it.bz.opendatahub.analytics#96]
Similarly to the "BikeCounter layer", developed in the same way as "Traffic", the request is to add the layer "**Bike Parking**", with the same look & feel as "Parking". The data to be visualized are to be retrieved from https://mobility.api.opendatahub.testingmachine.eu/v2/flat,node/BikeParking/*/latest

**Comment by dulvui** [comment]
@rcavaliere BikeParking stations are now visible on testing
https://analytics.opendatahub.testingmachine.eu/

If you can't see them in the list, try clearing the cache. I had to do it to see it.

**Comment by rcavaliere** [comment]
@dulvui perfect! Exactly what I imagined. Let's leave this under release on production until this dataset is published.
