### ISSUE TITLE
As an Open Data Hub user interested in traffic events I would like to have an improved visualization of such events on analytics.opendatahub.com

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/it.bz.opendatahub.analytics#97]
Following improvements should be implemented:

**Layer "Events"**

- [x] the filter on the time range is not usable since the number of "open date" events, i.e. without given end-date, is very large. We should have a way to filter them. Proposal: consider an additional "tick" field in the top horizontal bar, e.g. "Include Open Date Events". If activated, these open date events are returned, otherwise they are not provided and only the events with given start and end dates (i.e. for events in which we have a date) are returned
- [x] add a sorting function for the "legend" row of the table. In this way, it is possible to sort the table as desired by the user (just one sorting at a time possible), e.g.:

- start time / end time: possibility to sort events from the older / newer ones
- start meter / end meter: possibility to sort events from north to south

**Map Overview**

- [x] A22 events: please disable this. We will have a specific Data Collector and source for that, and we could reproduce exactly the map visualization available on https://www.autobrennero.it/it/
- [x] PAB events: different sublayers have to be foreseen, as follows: 
- [x] Province BZ - Roadworks: as documented in the annex, the Province of BZ typically assign an end date to this category of event ("intralci viabilità in e fuori Alto Adige_cantiere | Verkehrsbehinderung für Zonen und aus. Südt._Baustelle"). The logic of the Province is to visualize on the map "current" events, defined as follows: now() >= start_date AND now() <= end_date. This kind of event should have as icon a "roadwork icon".
- [x] Province BZ - Temporary closures. In this case the reference sub_category is " intralci viabilità in e fuori Alto Adige_chiusura temporanea | Verkehrsbehinderung für Zonen und aus. Südt._kurzfristige oder zeitweilige Sperre ". If the events have an end_date, have to be treated as the roadworks. Events that have no end_date should be always visualized.
- [x] Province BZ - Other planned events. In this case the reference sub_categories are

- "intralci viabilità in e fuori Alto Adige_attenzione | Verkehrsbehinderung für Zonen und aus. Südt._Vorsicht". 
- "intralci viabilità in e fuori Alto Adige_caduta frana | Verkehrsbehinderung für Zonen und aus. Südt._Murenabgang und Strassenverlegung"
- "intralci viabilità in e fuori Alto Adige_manifestazione | Verkehrsbehinderung für Zonen und aus. Südt._Veranstaltungen"
- "intralci viabilità in e fuori Alto Adige_senso unico alternato con semafero | Verkehrsbehinderung für Zonen und aus. Südt._Ampelregelung"

These events have to be visualized if the now () = start_date (i.e., only the events occurring on the right day have to be visualized).

- [x] Province BZ - Real-time events. To be applied for all main category "Situazione attuale" (i.e. for all subcategories associated to it, e.g.  "Situazione attuale_code | Aktuelle Lage_Stau - Rückstau"), same visualization logic as Province BZ - Other planned events
- [x] Ensure that all subcategory is visualized differently, by considering the right icon. Check the ZIP file attached.

 @dulvui please have a look at this document with some examples taken from the web-application developed by the Province of Bolzano

[240203_ProvinceBZ-Events-VisualizationLogic.pdf](https://github.com/noi-techpark/it.bz.opendatahub.analytics/files/14151727/240203_ProvinceBZ-Events-VisualizationLogic.pdf)

[ICONE_EVENTI_PAB.zip](https://github.com/noi-techpark/it.bz.opendatahub.analytics/files/14151753/ICONE_EVENTI_PAB.zip)

**Comment by dulvui** [comment]
@rcavaliere Open end filter is now active on testing. The a22 events data on the map is now hidden too. 
https://analytics.opendatahub.testingmachine.eu/

Now I'll work on the sorting.

**Comment by rcavaliere** [comment]
@dulvui very good. Let me know how much effort demanding the sorting function is, before putting a lot of time in the implementation of this functionality. In the meantime, I will prepare a concept for the map visualization of the PAB events, now that we improved the categories types.

**Comment by dulvui** [comment]
@rcavaliere also sorting works now, looks a bit ugly, but it works :-)

**Comment by rcavaliere** [comment]
@dulvui wonderful! Yes, would be nice to work a little bit on the UX, it is not clear when the sorting is activated or not. I also noticed that the function is disable when the open end filter is disabled, isn't it? Otherwise very useful feature!

**Comment by dulvui** [comment]
@rcavaliere The sorting works now correctly also on A22 data. I also optimized a bit the UI/UX

**Comment by dulvui** [comment]
I nearly forgot, the table of the events view is now a webcomponent int the testing store
https://webcomponents.opendatahub.testingmachine.eu/webcomponent/reactive-table

I think it was always supposed to be deployed, but I forgot about it. Now its also integrated into analytics as webcomponent, so when I update it, analytics automatically has the latest version on it.

**Comment by rcavaliere** [comment]
> @rcavaliere The sorting works now correctly also on A22 data. I also optimized a bit the UI/UX

Wonderful, that's perfect!

**Comment by rcavaliere** [comment]
@dulvui I have adjusted the text of the user story indicating how we should visualize on map the events of the Province of Bolzano. Once this is implemented we can close this user story and put the test new version of analytics in production.

**Comment by dulvui** [comment]
@rcavaliere I implemented now the logic for the ProvinceBZ events. I had to add the image of the bicycle shield we where missing and I simply copied it from the province website. I also temporary disabled clustering to be able to compare both maps better.

Here a screenshot of the comparison of our map and the province map https://verkehr.provinz.bz.it/default.asp and they look very similar now.
![image](https://github.com/noi-techpark/it.bz.opendatahub.analytics/assets/12729238/1af5d59c-43ab-428c-9000-9c533cae2fb1)

Some issues I still noticed is that we show some events that have no end date, but the rest looks pretty good.

**Comment by rcavaliere** [comment]
@dulvui very nice work!!! Let me check in detail these few issues, and then we can start to put into production the new version of analytics

**Comment by rcavaliere** [comment]
@dulvui looks everything very good now. What I have just observed is that for the "Province BZ - Real-time events" we need to display just the events that occurred on that day (warning: just this type of event has to behave like this!). My idea is to implement something like 

- control of the day of the event (field evstart)
- if the day of the event is = today then consider in the visualization, otherwise not

Can you implement this? I think that once this last configuration is carried out, we can put this new version of analytics in production

**Comment by dulvui** [comment]
@rcavaliere I fixed now the issue with this real time events and they only visible if they happened today.
Now its seems nearly perfect. The main differences to https://verkehr.provinz.bz.it/default.asp are that we still show some really old data about "passi"

![image](https://github.com/noi-techpark/it.bz.opendatahub.analytics/assets/12729238/19f0f67e-631a-48b8-9ed3-a3cfb93561d1)

And that they only show active "code/stau" and we show them all day, also if the "coda/stau" is already over. But this would be solvable only on datacollector level.

**Comment by rcavaliere** [comment]
@dulvui thanks. For the queues, accidents and similar events, perfect! For the mountain closures, I would treat them as for "Province BZ - Temporary closures", see above in the issue the proposed rule for the visualization!

**Comment by dulvui** [comment]
@rcavaliere great! the mountain closures have that logic, and because they don't have a end date, they still show up.
I'll deploy to production this afternoon, so we can close some old issues related to this and open new ones, of there are still issues. Is that fine for you?
